version: '3'
services:
  chatui:
    image: yourdockerhubusername/chatui:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/chat
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: